#! /bin/sh

chosen=$(printf "  Power Off\n  Restart\n  Log Out\n  Lock" | rofi -dmenu -i -theme-str '@import "power.rasi"')

case "$chosen" in
	"  Power Off") poweroff ;;
	"  Restart") reboot ;;
	"  Log Out") qtile cmd-obj -o cmd -f shutdown ;;
    "  Lock") betterlockscreen -l -u ~/Pictures/Wallpapers/shinobu.png;;
	*) exit 1 ;;
esac
